# Generated by Django 3.1.12 on 2025-03-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application_1', '0005_auto_20250226_1313'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datasetmetadata',
            constraint=models.UniqueConstraint(fields=('dataset_name', 'projet'), name='unique_dataset_per_project'),
        ),
    ]
